version: "3"
services:
  app:
    image: node:alpine
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
    ports:
      - 3000:3000
      - 9229:9229
    command: >
      sh -c "npm install &&
             npm start"
  mongo:
    image: mongo
    environment:
      - AUTH=no
    expose:
      - 27017
    volumes:
      - ./data/mongodb:/data/db