version: "3"
services:
  api:
    image: node:alpine
    working_dir: /usr/src/app
    volumes:
      - ./api:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
    ports:
      - 3000:3000
      - 9229:9229
    command: >
      sh -c "npm install &&
             npm start"
  app:
    image: node:alpine
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
    ports:
      - 3001:3000
    depends_on:
      - api
    command: >
      sh -c "npm install &&
             npm start"
  mongo:
    image: mongo
    environment:
      - AUTH=no
    expose:
      - 27017
    volumes:
      - mongodbdata:/data/db
volumes:
  mongodbdata:
    external: true
